# Generated by Django 4.2.2 on 2023-06-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='price',
            field=models.CharField(default='90', max_length=3),
        ),
    ]
